name: profile automation
on:
  push:
  schedule:
    - cron:  '0 4 * * 1-6'
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: retrieve repositories
      shell: pwsh
      run: |
        $repos = gh repo list Dexmach --public --json isArchived,name,repositoryTopics,url
        $repoList = $repos | ConvertFrom-Json
        $archivedRepos = $repoList.where({$_.IsArchived -eq $true})
        $aiwRepos = $repoList.where({($_.RepositoryTopics.name -eq 'aiw') -and ($_.IsArchived -eq $false)})
        $ossRepos = $repoList.where({($_.RepositoryTopics.name -eq 'oss') -and ($_.IsArchived -eq $false)})
        $readme = get-content ./profile/README.md
        
        foreach ($repo in $aiwRepos){$aiwOutput+= "- [{0}]({1})`r`n" -f $repo.Name, $repo.url }
        foreach ($repo in $ossRepos){$ossOutput+= "- [{0}]({1})`r`n" -f $repo.Name, $repo.url }
        foreach ($repo in $archivedRepos){$archivedOutput+= "- [{0}]({1})`r`n" -f $repo.Name, $repo.url }
        $readme = $readme.replace('{{ AIW }}', $aiwOutput)
        $readme = $readme.replace('{{ OPENSOURCE }}', $ossOutput)
        $readme = $readme.replace('{{ ARCHIVED }}', $archivedOutput)

        Set-Content -Path ./profile/README.md -Value $readme -Force
    - name: Commit profile README.MD
      run : |
          git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit --allow-empty -m "update list of repos"
            git push


